salario1: float = float(input("Digite o salário do funcionário 1: "))
salario2: float = float(input("Digite o salário do funcionário 2: "))   
nome1: str = input("Digite o nome do funcionário 1: ")
nome2: str = input("Digite o nome do funcionário 2: ")
idade: int = int(input("Digite a idade do funcionário 1: "))
idade2: int = int(input("Digite a idade do funcionário 2: "))
sexo1: str = input("Digite o sexo do funcionário 1 (M/F): ")
sexo2: str = input("Digite o sexo do funcionário 2 (M/F): ")

print(f"Nome 1: {nome1}")
print(f"Nome 2: {nome2}")
print(f"Salário 1: {salario1:.2f}")
print(f"Salário 2: {salario2:.2f}")
print(f"Idade 1: {idade}")
print(f"Idade 2: {idade2}")
print(f"Sexo 1: {sexo1}")
print(f"Sexo 2: {sexo2}")
